
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEarn.java
 *
 * Created on Dec 29, 2015, 1:14:31 PM
 */

/**
 *
 * @author Nilkanth
 */
public class AddEarn extends javax.swing.JFrame {

    /** Creates new form AddEarn */
    public AddEarn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Earnings");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rb1.setSelected(true);
        rb1.setText("Main Earning (Ex:- income)");
        rb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rb1MouseReleased(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        rb2.setText("Extra Earning (Ex:- reward)");
        rb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rb2MouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        jLabel1.setText("Type:-");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        jLabel2.setText("Extra earning title:-");

        tf_title.setEnabled(false);

        jLabel3.setText("Amount:-");

        amt.setText("0");

        jLabel4.setText("Month of earning:-");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amt)
                            .addComponent(tf_title, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb2)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
    Class.forName("java.sql.DriverManager");
    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp12cay" + globalvar.year,"root","admin");
    Statement st = c.createStatement();
    ResultSet x = st.executeQuery("select count(e_id) as y from earnings;");
    int e1 = 0;
    if(x.next()){
        e1 = (x.getInt("y")+1);
    }
    String e2=null,e3,e;
    if(rb1.isSelected()){
            e2 = "Income/Main Earning";
        }

        else if(rb2.isSelected() && !tf_title.getText().isEmpty())
        {
            e2 = tf_title.getText();
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid entries in fields.");
            return;
        }


        if((!amt.getText().isEmpty())&&(cb.getSelectedIndex()!=-1)){
            e3 = amt.getText();
            e = cb.getSelectedItem().toString();
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid entries in fields.");
            return;
        }

    int t = 0;
    while(t<=globalvar.frame3.tbEarn.getRowCount()-1 && rb1.isSelected()){
        if((e.equals(globalvar.frame3.tbEarn.getModel().getValueAt(t,3)))&&(globalvar.frame3.tbEarn.getModel().getValueAt(t,1).equals("Income/Main Earning"))){
            JOptionPane.showMessageDialog(null,"A month cannot have more than one income/main earnings.\nIf you have, add it as extra earning.");
            return;
        }
        else{t++;}
    }

    String prefix;
                if(e.equals("January")){
                prefix = "A_";
                }
                else if(e.equals("February")){
                prefix = "B_";
                }
                else if(e.equals("March")){
                prefix = "C_";
                }
                else if(e.equals("April")){
                prefix = "D_";
                }
                else if(e.equals("May")){
                prefix = "E_";
                }
                else if(e.equals("June")){
                prefix = "F_";
                }
                else if(e.equals("July")){
                prefix = "G_";
                }
                else if(e.equals("August")){
                prefix = "H_";
                }
                else if(e.equals("September")){
                prefix = "I_";
                }
                else if(e.equals("October")){
                prefix = "J_";
                }
                else if(e.equals("November")){
                prefix = "K_";
                }
                else{
                prefix = "L_";
                }
    String e4 = prefix + e;
    st.executeUpdate("insert into earnings values("+e1+", '"+e2+"', "+e3+", '"+e4+"');");

    //Clear table before reloading
    DefaultTableModel model = (DefaultTableModel)globalvar.frame3.tbEarn.getModel();
    while(model.getRowCount()>0){
    model.removeRow(0);
    }
    
            Statement stat = c.createStatement();
            ResultSet earnings = stat.executeQuery("select * from earnings order by month;");
            DefaultTableModel m = (DefaultTableModel) globalvar.frame3.tbEarn.getModel();
            while(earnings.next()){
                String s1 = earnings.getString("e_id");
                String s2 = earnings.getString("title");
                String s3 = earnings.getString("amount");
                String s = earnings.getString("month").substring(2);
                String s4 = s.substring(0,1).toUpperCase() + s.substring(1);
                m.addRow(new Object[]{s1,s2,s3,s4});
            }
            this.dispose();
    }
    catch(Exception k){
    JOptionPane.showMessageDialog(null, k.getMessage());
    }

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    //Add items to combobox cb
    int i = 0;
    while(i<=globalvar.frame1.tb1.getRowCount()-1){
        cb.addItem(globalvar.frame1.tb1.getValueAt(i,0));
        i++;
    }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseReleased
    tf_title.setEnabled(true);
    }//GEN-LAST:event_rb2MouseReleased

    private void rb1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseReleased
    tf_title.setEnabled(false);
    }//GEN-LAST:event_rb1MouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEarn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tf_title;
    // End of variables declaration//GEN-END:variables

}
