import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Report.java
 *
 * Created on Jan 3, 2016, 4:28:06 PM
 */

/**
 *
 * @author Nilkanth
 */
public class Report extends javax.swing.JFrame {

    /** Creates new form Report */
    public Report() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        education = new javax.swing.JProgressBar();
        transport = new javax.swing.JProgressBar();
        food = new javax.swing.JProgressBar();
        billing = new javax.swing.JProgressBar();
        insurance = new javax.swing.JProgressBar();
        tax = new javax.swing.JProgressBar();
        loan = new javax.swing.JProgressBar();
        medical = new javax.swing.JProgressBar();
        property = new javax.swing.JProgressBar();
        maid = new javax.swing.JProgressBar();
        entertainment = new javax.swing.JProgressBar();
        clothing = new javax.swing.JProgressBar();
        other = new javax.swing.JProgressBar();
        total = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel1.setText("Education");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel2.setText("Food");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3.setText("Transportation Expense");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 71, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel4.setText("Billing Expense");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 101, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel5.setText("Insurance");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 131, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel6.setText("Tax");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 161, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel7.setText("Loan Activity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 191, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel8.setText("Medical Expense");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 221, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel9.setText("Property Expense");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 251, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel10.setText("Maid/Servant Expense");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 281, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel11.setText("Entertainment");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 311, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel12.setText("Clothing");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 341, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel13.setText("Others...");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 371, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel14.setText("TOTAL");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 408, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 392, 710, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 710, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 710, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 710, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 710, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 710, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 710, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 710, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 710, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 710, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 710, -1));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 450));

        education.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        education.setString("Rs.0            0% of earnings");
        education.setStringPainted(true);
        jPanel1.add(education, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 500, 15));

        transport.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        transport.setString("Rs.0            0% of earnings");
        transport.setStringPainted(true);
        jPanel1.add(transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 500, 15));

        food.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        food.setString("Rs.0            0% of earnings");
        food.setStringPainted(true);
        jPanel1.add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 500, 15));

        billing.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        billing.setString("Rs.0            0% of earnings");
        billing.setStringPainted(true);
        jPanel1.add(billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 500, 15));

        insurance.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        insurance.setString("Rs.0            0% of earnings");
        insurance.setStringPainted(true);
        jPanel1.add(insurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 500, 15));

        tax.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        tax.setString("Rs.0            0% of earnings");
        tax.setStringPainted(true);
        jPanel1.add(tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 500, 15));

        loan.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        loan.setString("Rs.0            0% of earnings");
        loan.setStringPainted(true);
        jPanel1.add(loan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 500, 15));

        medical.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        medical.setString("Rs.0            0% of earnings");
        medical.setStringPainted(true);
        jPanel1.add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 500, 15));

        property.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        property.setString("Rs.0            0% of earnings");
        property.setStringPainted(true);
        jPanel1.add(property, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 500, 15));

        maid.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        maid.setString("Rs.0            0% of earnings");
        maid.setStringPainted(true);
        jPanel1.add(maid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 500, 15));

        entertainment.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        entertainment.setString("Rs.0            0% of earnings");
        entertainment.setStringPainted(true);
        jPanel1.add(entertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 500, 15));

        clothing.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        clothing.setString("Rs.0            0% of earnings");
        clothing.setStringPainted(true);
        jPanel1.add(clothing, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 500, 15));

        other.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        other.setString("Rs.0            0% of earnings");
        other.setStringPainted(true);
        jPanel1.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 500, 15));

        total.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        total.setString("");
        total.setStringPainted(true);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 500, 15));

        jButton1.setText("<-- Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 255, 51));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("EXPENSE REPORT");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        jLabel15.setOpaque(true);

        lblMonth.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        lblMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMonth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(248, 248, 248)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.getContentPane().setBackground(new Color(20,60,255,150));
    try{
        Class.forName("java.sql.DriverManager");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp12cay" + globalvar.year,"root","admin");
        Statement s1 = conn.createStatement();
        Statement s2 = conn.createStatement();
        ResultSet r1 = s1.executeQuery("select category,sum(spent) from " + globalvar.tablename + " group by category;");
        ResultSet r2 = s2.executeQuery("select sum(Amount) as a from earnings where month = '" + globalvar.tablename + "';");
        lblMonth.setText("Report of " + globalvar.tablename.substring(2,3).toUpperCase() + globalvar.tablename.substring(3));
        float erng=0;
        if(r2.next()){
            erng = r2.getInt("a");
        }
        else{
            JOptionPane.showMessageDialog(null,"No earnings found.");
            this.dispose();
            globalvar.frame1.setVisible(true);
        }
        
        String cat=null;
        float spt = 0;
        float temp = 0;
        int sumExp=0;
        if(r1.next()){
            r1.beforeFirst();
            while(r1.next()){
                cat = r1.getString("category");
                spt = Float.parseFloat(r1.getString("sum(spent)"));
                temp = (float) (Math.round((spt * 10000.0) / erng) / 100.0);

                if(cat.equalsIgnoreCase("education")){                    
                    education.setValue(Math.round(temp));
                    education.setString("Rs." + spt + "            " + temp + "% of earnings");

                }
                else if(cat.equalsIgnoreCase("food")){
                    food.setValue(Math.round(temp));
                    food.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("transportation expense")){
                    transport.setValue(Math.round(temp));
                    transport.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("billing expense")){
                    billing.setValue(Math.round(temp));
                    billing.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("insurance")){
                    insurance.setValue(Math.round(temp));
                    insurance.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("tax")){
                    tax.setValue(Math.round(temp));
                    tax.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("loan activity")){
                    loan.setValue(Math.round(temp));
                    loan.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("medical expense")){
                    medical.setValue(Math.round(temp));
                    medical.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("property expense")){
                    property.setValue(Math.round(temp));
                    property.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("maid/servant expense")){
                    maid.setValue(Math.round(temp));
                    maid.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("entertainment")){
                    entertainment.setValue(Math.round(temp));
                    entertainment.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("clothing")){
                    clothing.setValue(Math.round(temp));
                    clothing.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                else if(cat.equalsIgnoreCase("others...")){
                    other.setValue(Math.round(temp));
                    other.setString("Rs." + spt + "            " + temp + "% of earnings");
                }
                sumExp = sumExp + Math.round(spt);
            }
            if(sumExp>erng){
                JOptionPane.showMessageDialog(null,"<html><font color = 'red'>ERROR:</font>Expenses are getting higher than earnings.<br>Cannot generate report.</html>");
                this.dispose();
                globalvar.frame1.setVisible(true);

            }
            else{
                float val = (sumExp*100)/erng;
                total.setValue(Math.round(val));
                float val2 = 100 - val;
                total.setString("Expenses  = " + Math.round(val) + "% and Savings = " + Math.round(val2) + "%");
                                
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No expenses found.");//TABLE EMPTY
            this.dispose();
            globalvar.frame1.setVisible(true);
        }
    }
    catch(Exception k){
        JOptionPane.showMessageDialog(null,k.getMessage());
    }    
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.dispose();
            globalvar.frame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            this.dispose();
            globalvar.frame1.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar billing;
    private javax.swing.JProgressBar clothing;
    private javax.swing.JProgressBar education;
    private javax.swing.JProgressBar entertainment;
    private javax.swing.JProgressBar food;
    private javax.swing.JProgressBar insurance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JProgressBar loan;
    private javax.swing.JProgressBar maid;
    private javax.swing.JProgressBar medical;
    private javax.swing.JProgressBar other;
    private javax.swing.JProgressBar property;
    private javax.swing.JProgressBar tax;
    private javax.swing.JProgressBar total;
    private javax.swing.JProgressBar transport;
    // End of variables declaration//GEN-END:variables

}
